name: Acebook CI/CD Workflow

on:
  push:
    branches: [ main, test-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  simple-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List repository contents
      run: ls -la
      
    - name: Simple echo test
      run: echo "This is a simple test that should always pass!"
      
    - name: Notify on success
      if: success()
      run: echo "CI pipeline completed successfully!"