name: Acebook CI/CD Workflow

on:
  push:
    branches: [ main, test-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # Install MongoDB
    - name: Install MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb

    # Start MongoDB
    - name: Start MongoDB
      run: |
        sudo systemctl start mongod

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npm run lint

    - name: Notify on success
      if: success()
      run: echo "CI pipeline completed successfully!"