name: Acebook CI/CD Workflow

on:
  push:
    branches: [ main, test-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # Install MongoDB from MongoDB's official repository
    - name: Install MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
        echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org

    # Start MongoDB
    - name: Start MongoDB
      run: |
        sudo systemctl start mongod
        sudo systemctl enable mongod  # Ensure MongoDB starts on boot
        sleep 10  # Wait for MongoDB to start (adjust time if needed)

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npm run lint

    - name: Notify on success
      if: success()
      run: echo "CI pipeline completed successfully!"